# Configuration options for your blog - customise to taste
# This file contains no secret information, so can be stored in source control (unlike database.yml)
title: Pinball Map Blog
url:   http://blog.pinballmap.com
author:
  name:    Pinball Map Blog # For copyright notice and ATOM feeds
  email:   master.cob@gmail.com # Exception emails will go here, and it is used in ATOM feeds
  open_id:                  # These are used to login to the admin area
      - https://profiles.google.com/111944412963212113223 #ryan
      - https://profiles.google.com/111209230997429502793 #scott
